// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdjfwuaevdfxegcyoirw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkamZ3dWFldmRmeGVnY3lvaXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODYxMTIsImV4cCI6MjA1Nzk2MjExMn0.q7CDJVs8mFYTd25105HKJXXIT0xDcbykVwQo8ObsLLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);